.test_template: &test_definition
  # Uncomment below if you would like to run the tests on specific references
  # only, such as the branches `master`, `development`, etc.
  # only:
  #   - master
  #   - development
  script:
    - julia -e 'using Pkg; Pkg.add(url="https://github.com/JuliaHEP/LVCyl.jl", rev="master"); Pkg.add(path="."); Pkg.build("WVZAnalysis"); Pkg.test("WVZAnalysis"; coverage = true)'
    - julia -e 'using Pkg; Pkg.add("Coverage");
      import WVZAnalysis; cd(joinpath(dirname(pathof(WVZAnalysis)), ".."));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'

test:1.7:
  image: julia:1.7
  <<: *test_definition

pages:
  image: julia
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y git  # needed by Documenter
    - julia -e 'using Pkg; Pkg.add(url="https://github.com/JuliaHEP/LVCyl.jl", rev="master"); Pkg.add(path="."); Pkg.build("WVZAnalysis");'
    - julia -e 'using Pkg; import WVZAnalysis; Pkg.add("Documenter")'  # install Documenter
    - julia --color=yes docs/make.jl  # make documentation
    - mv docs/build public  # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master
